# Build docker image from master and push it to GitHub packages
name: Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: package docker
        run: |
          cat src/typeDefs/types/playerType.js
          docker login docker.pkg.github.com --username Tallcraft --password ${{ secrets.GITHUB_TOKEN }}
          docker build . --file Dockerfile --tag docker.pkg.github.com/tallcraft/tc-api-server/app:master
          docker push docker.pkg.github.com/tallcraft/tc-api-server/app:master
        env:
          CI: true
